spring.application.name=rh

server.address=0.0.0.0
server.port=8086

spring.datasource.url=jdbc:dbeaver:libsql:https://rh-mahefa.aws-us-west-2.turso.io
                                   
spring.datasource.username=

spring.datasource.password=${TURSO_AUTH_TOKEN}

spring.datasource.driver-class-name=com.dbeaver.jdbc.driver.libsql.LibSqlDriver

spring.jpa.defer-datasource-initialization=true
# ==========================================================
# HIKARI
# ==========================================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.connection-test-query=SELECT 1


# ==========================================================
# INITIALISATION SQL
# ==========================================================

spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:schema.sql


# ==========================================================
# THYMELEAF
# ==========================================================

spring.thymeleaf.cache=false