spring.application.name=rh
server.address=0.0.0.0
server.port=8086

# ==========================================================
# TURSO
# ==========================================================
app.datasource.turso.jdbc-url=jdbc:dbeaver:libsql:https://rh-mahefa.aws-us-west-2.turso.io
app.datasource.turso.username=
app.datasource.turso.password=${TURSO_AUTH_TOKEN}
app.datasource.turso.driver-class-name=com.dbeaver.jdbc.driver.libsql.LibSqlDriver
app.datasource.turso.maximum-pool-size=5
app.datasource.turso.minimum-idle=1
app.datasource.turso.connection-test-query=SELECT 1

# ==========================================================
# SQL SERVER (interne)
# ==========================================================
app.datasource.sqlserver.jdbc-url=jdbc:sqlserver://26.53.123.231:1433;databaseName=rh_pointage;encrypt=true;trustServerCertificate=true
app.datasource.sqlserver.username=dev
app.datasource.sqlserver.password=1234
app.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.sqlserver.maximum-pool-size=10
app.datasource.sqlserver.minimum-idle=2
app.datasource.sqlserver.connection-test-query=SELECT 1

# ==========================================================
# INITIALISATION SQL : désactivée (voir plus bas)
# ==========================================================
spring.sql.init.mode=never

spring.thymeleaf.cache=false